[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.71.0",
    "pydub>=0.25.1",
    "pytelegrambotapi>=4.26.0",
    "requests>=2.32.3",
]
